# Generated by Django 3.0.5 on 2020-05-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200525_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='doctor',
        ),
    ]
