# Generated by Django 3.0.5 on 2020-05-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accounting_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor'),
        ),
    ]
