# Generated by Django 3.0.5 on 2020-05-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounting_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='item_price',
            new_name='imedicines_price',
        ),
        migrations.RenameField(
            model_name='accounting',
            old_name='item',
            new_name='medicines',
        ),
    ]
