# Generated by Django 3.0.5 on 2020-05-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200525_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='imedicines_price',
            new_name='medicines_price',
        ),
    ]
